Can service
farochmehri/canbus-ht19 pull request #25
Opened 2020-10-31 00:42 UTC by BengtCruz

2020-11-01 17:09 UTC, farochmehri requested changes
Read the reviews and fix the issues.

2020-11-01 17:09 UTC, farochmehri commented on can_service/can_service.cpp
> +// DO NOT EDIT THIS FILE BY HAND!!
This file shall be generated by the script in the lib/canbus directory of the target repository

2020-11-01 17:09 UTC, farochmehri commented on can_service/can_service.cpp
> +// Generated for node HUMAN MACHINE INTERFACE// Timestamp: 2020-10-31T01:33:31
The description shall be according to doxygen

2020-11-01 17:09 UTC, farochmehri commented on can_service/can_service.h
> +#ifndef CAN_SERVICE_H
Describe the file

2020-11-01 17:09 UTC, farochmehri commented on can_service/can_signal.h
> +#ifndef CAN_SIGNAL_H
Describe the file

2020-11-01 17:09 UTC, farochmehri commented on can_service/can_signal.h
> + * @param msg_index
Describe the parameters

2020-11-01 17:09 UTC, farochmehri commented on can_service/service.py
> +        if signal['getters'] == node or node in signal['setters']:
It shall be if node in signal['getters'] or node in signal['setters']:

2020-11-02 11:05 UTC, JesperMell reviewed
This is some good Python!

2020-11-03 13:08 UTC, merged